// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth/forgot-password': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/auth/forgot-password.post').default>>>>
    }
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/auth/login.post').default>>>>
    }
    '/api/auth/logout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/auth/logout.post').default>>>>
    }
    '/api/auth/profile': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/auth/profile.put').default>>>>
    }
    '/api/auth/reset-password': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/auth/reset-password.post').default>>>>
    }
    '/api/auth/signup': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/auth/signup.post').default>>>>
    }
    '/api/auth/user': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/auth/user.get').default>>>>
    }
    '/api/auth/verify': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/auth/verify.get').default>>>>
    }
    '/api/dashboard/summary': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/dashboard/summary.get').default>>>>
    }
    '/api/subscription/cancel': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/subscription/cancel.post').default>>>>
    }
    '/api/subscription/checkout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/subscription/checkout.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/#internal/nuxt/island-renderer').default>>>>
    }
    '/_ipx/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/image/dist/runtime/ipx').default>>>>
    }
  }
}
export {}