// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/11/2025, 8:15:28 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/user/Documents/GitHub/qwesi-home/src/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/user/Documents/GitHub/qwesi-home/src/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/user/Documents/GitHub/qwesi-home/src/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/user/Documents/GitHub/qwesi-home/src/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/user/Documents/GitHub/qwesi-home/src/plugins/**/*.{js,ts,mjs}","/Users/user/Documents/GitHub/qwesi-home/src/composables/**/*.{js,ts,mjs}","/Users/user/Documents/GitHub/qwesi-home/src/utils/**/*.{js,ts,mjs}","/Users/user/Documents/GitHub/qwesi-home/src/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/user/Documents/GitHub/qwesi-home/src/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/user/Documents/GitHub/qwesi-home/src/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/user/Documents/GitHub/qwesi-home/src/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;